POST http://localhost:3002/tokens
Content-Type: application/json

{
  "user": "renan.winter@gmail.com",
  "validity": "2024-12-31T16:00:00.000-03:00"
}


### Listar eventos
GET http://localhost:3002/events


### Cadastrar Evento
POST http://localhost:3002/events
Content-Type: application/json

{
  "name": "New Event",
  "description": "event description",
  "date": "2020-01-01T20:00:00",
  "price": 150.85
}


### Recuperar Evento por ID
GET http://localhost:3002/events/b8cd5bee-e727-4f61-a6e5-341e6f745f75


### Atualizar evento
PATCH http://localhost:3002/events/b8cd5bee-e727-4f61-a6e5-341e6f745f75
Content-Type: application/json

{
  "name": "Banda Loading Shows",
  "date": "2020-01-01T20:00:00"
}

### Exclui Evento por ID
DELETE http://localhost:3002/events/b8cd5bee-e727-4f61-a6e5-341e6f745f75


### adicionar spot a um evento
POST http://localhost:3002/events/b8cd5bee-e727-4f61-a6e5-341e6f745f75/spots
Content-Type: application/json

{
  "name": "L10"
}

### lista de spots do evento
GET http://localhost:3002/events/b8cd5bee-e727-4f61-a6e5-341e6f745f75/spots


### remover spot
DELETE http://localhost:3002/events/b8cd5bee-e727-4f61-a6e5-341e6f745f75/spots/19173dc7-6c5e-45cd-83d7-a8bc6bdc5937


### reserve spots
POST http://localhost:3002/events/b8cd5bee-e727-4f61-a6e5-341e6f745f75/reserve
Content-Type: application/json

{
  "spots": [
    {"spot": "L5","kind": "full"}

  ],
  "email": "renan.winter@gmail.com"
}